const weatherIconsData = {
  day: {
    clear: "/images/weather/day_clear.png",
    partlycloudy: "/images/weather/day_partial_cloud.png",
    cloudywithsunnyintervals: "/images/weather/day_partial_cloud.png",
    cloudy: "/images/weather/overcast.png",
    thunder: "/images/weather/rain_thunder.png",
    isolatedthunderstorms: "/images/weather/day_rain_thunder.png",
    thunderstorms: "/images/weather/rain_thunder.png",
    heavyrainwiththunderstorms: "/images/weather/rain_thunder.png",
    lightrain: "/images/weather/rain.png",
    rain: "/images/weather/rain.png",
    heavyrain: "/images/weather/rain.png",
    lightsleet: "/images/weather/day_sleet.png",
    sleet: "/images/weather/sleet.png",
    freezingrain: "/images/weather/sleet.png",
    hail: "/images/weather/rain_thunder",
    lightsnow: "/images/weather/day_snow.png",
    snow: "/images/weather/snow.png",
    heavysnow: "/images/weather/snow.png",
    fog: "/images/weather/fog.png",
    null: "/images/weather/day_clear.png",
  },
  night: {
    clear: "/images/weather/night_clear.png",
    partlycloudy: "/images/weather/night_partial_cloud.png",
    cloudywithsunnyintervals: "/images/weather/night_partial_cloud.png",
    cloudy: "/images/weather/overcast.png",
    thunder: "/images/weather/rain_thunder.png",
    isolatedthunderstorms: "/images/weather/night_rain_thunder.png",
    thunderstorms: "/images/weather/rain_thunder.png",
    heavyrainwiththunderstorms: "/images/weather/rain_thunder.png",
    lightrain: "/images/weather/rain.png",
    rain: "/images/weather/rain.png",
    heavyrain: "/images/weather/rain.png",
    lightsleet: "/images/weather/night_sleet.png",
    sleet: "/images/weather/sleet.png",
    freezingrain: "/images/weather/sleet.png",
    hail: "/images/weather/rain_thunder",
    lightsnow: "/images/weather/night_snow.png",
    snow: "/images/weather/snow.png",
    heavysnow: "/images/weather/snow.png",
    fog: "/images/weather/fog.png",
    null: "/images/weather/night_clear.png",
  },
};

export default weatherIconsData;
